"""add jobs.payload column

Revision ID: 0bbbc430cd99
Revises: 0fc46f190ead
Create Date: 2026-06-28 05:52:55.214701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bbbc430cd99'
down_revision: Union[str, Sequence[str], None] = '0fc46f190ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('payload', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'payload')
    # ### end Alembic commands ###
