"""add clip_candidate discord coordination fields

Revision ID: c8972e212b4e
Revises: 0bbbc430cd99
Create Date: 2026-06-28 06:36:06.331092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8972e212b4e'
down_revision: Union[str, Sequence[str], None] = '0bbbc430cd99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clip_candidates', sa.Column('claimed_by', sa.String(length=120), nullable=True))
    op.add_column('clip_candidates', sa.Column('discord_message_id', sa.String(length=64), nullable=True))
    op.add_column('clip_candidates', sa.Column('discord_thread_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_clip_candidates_discord_message_id'), 'clip_candidates', ['discord_message_id'], unique=False)
    op.create_index(op.f('ix_clip_candidates_discord_thread_id'), 'clip_candidates', ['discord_thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clip_candidates_discord_thread_id'), table_name='clip_candidates')
    op.drop_index(op.f('ix_clip_candidates_discord_message_id'), table_name='clip_candidates')
    op.drop_column('clip_candidates', 'discord_thread_id')
    op.drop_column('clip_candidates', 'discord_message_id')
    op.drop_column('clip_candidates', 'claimed_by')
    # ### end Alembic commands ###
